#!/usr/bin/env python3
"""Generate examples/internal/.gitlab-ci.yml ``spec:inputs`` from seed artifacts.

Jenkins seed embeds CLUSTER_ID / PHASES / LIMIT into Job DSL. GitLab has no
Active Choices — dropdowns are static ``options`` / ``rules`` in the main CI
file. Re-run this after inventory changes (GitLab job ``seed``), then commit.

Reads (from ``examples/internal/seed/`` by default):

* ``cluster-ids.txt`` — deployable leaf ids (one per line)
* ``cluster-phases.json`` — ``{cluster_id: [phase, …]}``
* ``cluster-limits.json`` — UI list ``[{value,label},…]`` or legacy shapes

Writes: ``examples/internal/.gitlab-ci.yml`` (header + include jobs body).

Usage::

  python3 examples/internal/seed/generate_gitlab_ci.py \\
    --ids examples/internal/seed/cluster-ids.txt \\
    --phases examples/internal/seed/cluster-phases.json \\
    --limits examples/internal/seed/cluster-limits.json \\
    --output examples/internal/.gitlab-ci.yml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


NONE_SENTINEL = "__none__"


def _q(s: str) -> str:
    """YAML double-quoted scalar."""
    return json.dumps(str(s), ensure_ascii=False)


def _limit_values(entry: object) -> list[str]:
    """Extract inventory keys for LIMIT options (ignore UI labels)."""
    out: list[str] = []
    if isinstance(entry, list) and entry and isinstance(entry[0], dict):
        for item in entry:
            if not isinstance(item, dict):
                continue
            value = item.get("value")
            if value is not None and str(value).strip():
                out.append(str(value).strip())
        return out
    if isinstance(entry, list):
        return [str(x).strip() for x in entry if str(x).strip()]
    if isinstance(entry, dict):
        return [str(k).strip() for k in entry.keys() if str(k).strip()]
    return out


def _options_with_none(values: list[str]) -> list[str]:
    """GitLab requires ≥1 option + default ∈ options; ``__none__`` = empty selection.

    Also offer a CSV of all values when there are 2+ (string inputs are single-select;
    GitLab ``type: array`` + ``rules`` cannot satisfy both scalar-in-options and
    array-typed default checks).
    """
    cleaned = [v for v in values if v and v != NONE_SENTINEL]
    out = [NONE_SENTINEL]
    if len(cleaned) > 1:
        joined = ",".join(cleaned)
        if joined not in cleaned:
            out.append(joined)
    out.extend(cleaned)
    return out


def _options_block(values: list[str], indent: int) -> str:
    pad = " " * indent
    lines = [f"{pad}options:"]
    for v in values:
        lines.append(f"{pad}  - {_q(v)}")
    return "\n".join(lines)


def _rule_for_cid(cid: str, values: list[str]) -> list[str]:
    opts = _options_with_none(values)
    lines = [f"        - if: $[[ inputs.cluster_id ]] == {_q(cid)}", "          options:"]
    for v in opts:
        lines.append(f"            - {_q(v)}")
    # Must be a scalar ∈ options (rules check). Input type is string for the
    # same reason — array defaults fail rules; scalar defaults fail array type.
    lines.append(f"          default: {_q(NONE_SENTINEL)}")
    return lines


def _fallback_rule() -> list[str]:
    opts = _options_with_none([])
    lines = ["        - options:"]
    for v in opts:
        lines.append(f"            - {_q(v)}")
    lines.append(f"          default: {_q(NONE_SENTINEL)}")
    return lines


def build_gitlab_ci(
    ids: list[str],
    phases_map: dict[str, list[str]],
    limits_map: dict[str, list[str]],
    *,
    prefer: str = "",
) -> str:
    if not ids:
        raise SystemExit("generate_gitlab_ci: cluster id list is empty")

    ordered = list(ids)
    if prefer and prefer in ordered:
        ordered = [prefer] + [i for i in ordered if i != prefer]
    default_cid = ordered[0]

    # GitLab: type array + rules is impossible (rules need scalar default ∈
    # options; array type needs array default). Use string + cascade; CSV option
    # covers "all values" when len>1. Sentinel __none__ → empty (plan SoT / omit).
    phase_rules: list[str] = []
    for cid in ordered:
        phases = [str(p).strip() for p in (phases_map.get(cid) or []) if str(p).strip()]
        phase_rules.extend(_rule_for_cid(cid, phases))
    phase_rules.extend(_fallback_rule())

    limit_rules: list[str] = []
    for cid in ordered:
        limits = limits_map.get(cid) or []
        limit_rules.extend(_rule_for_cid(cid, limits))
    limit_rules.extend(_fallback_rule())
    parts = [
        "# AUTO-GENERATED by examples/internal/seed/generate_gitlab_ci.py",
        "# Do not hand-edit cluster_id / phases / limit options — re-run GitLab job",
        "# ``seed`` (or the generator locally) after inventory leaf / hosts / phases",
        "# changes. Hand-maintained jobs: examples/internal/gitlab-ci.jobs.yml",
        "#",
        "# Wire as the project CI config path (required for Run-pipeline INPUTS UI):",
        "#   Settings → CI/CD → CI/CD configuration file → examples/internal/.gitlab-ci.yml",
        "# Docs: docs/gitlab-ci.md",
        "",
        "spec:",
        "  inputs:",
        "    cluster_id:",
        "      type: string",
        f"      default: {_q(default_cid)}",
        '      description: "Deployable leaf (seeded from inventory; like Jenkins CLUSTER_ID)"',
        _options_block(ordered, 6),
        "    phases:",
        "      type: string",
        '      description: "Phase name or CSV. __none__ = plan SoT (no --phases)"',
        "      rules:",
        *phase_rules,
        "    limit:",
        "      type: string",
        '      description: "Inventory group/host or CSV. __none__ = omit --limit"',
        "      rules:",
        *limit_rules,
        "    tags:",
        "      type: string",
        '      default: ""',
        '      description: "Ansible --tags on Run (empty or all = catalog)"',
        "    extra_vars:",
        "      type: string",
        '      default: ""',
        '      description: "Space-separated key=value (no leading -e)"',
        "    inventory_git_url:",
        "      type: string",
        '      default: ""',
        '      description: "Deploy only: inventory git URL override (empty = CI/CD var INVENTORY_GIT_URL)"',
        "    inventory_git_ref:",
        "      type: string",
        '      default: "main"',
        '      description: "Deploy only: inventory branch (empty input still yields main)"',
        "    inventory_dir:",
        "      type: string",
        '      default: "atlas-inventory"',
        '      description: "Deploy only: inventory checkout directory"',
        "    prefer_cluster_id:",
        "      type: string",
        '      default: ""',
        '      description: "Seed only: put this id first in cluster_id options if present"',
        "    validate_strict:",
        "      type: string",
        '      default: "off"',
        "      options:",
        '        - "off"',
        '        - "--strict"',
        '      description: "Validate: off or --strict"',
        "    run_smoke:",
        "      type: boolean",
        "      default: true",
        '      description: "Run ./cluster smoke before plan/run"',
        "    skip_deploy:",
        "      type: boolean",
        "      default: false",
        '      description: "Plan only (skip ./cluster run)"',
        "    run_ci_preflight:",
        "      type: boolean",
        "      default: true",
        '      description: "Offline ci_preflight --skip-tests before repos sync"',
        "",
        "---",
        "",
        "stages:",
        "  - seed",
        "  - deploy",
        "",
        "variables:",
        '  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"',
        '  CLUSTER_ID: "$[[ inputs.cluster_id ]]"',
        '  PHASES: "$[[ inputs.phases ]]"',
        '  LIMIT: "$[[ inputs.limit ]]"',
        '  TAGS: "$[[ inputs.tags ]]"',
        '  EXTRA_VARS: "$[[ inputs.extra_vars ]]"',
        # Inventory URL/ref/dir are NOT mapped globally: seed uses project CI/CD
        # Variables (INVENTORY_GIT_URL, …). Empty Inputs must not wipe them.
        # Deploy binds optional input overrides via INPUT_INVENTORY_* in jobs.yml.
        '  PREFER_CLUSTER_ID: "$[[ inputs.prefer_cluster_id ]]"',
        '  VALIDATE_STRICT: "$[[ inputs.validate_strict ]]"',
        '  RUN_SMOKE: "$[[ inputs.run_smoke ]]"',
        '  SKIP_DEPLOY: "$[[ inputs.skip_deploy ]]"',
        '  RUN_CI_PREFLIGHT: "$[[ inputs.run_ci_preflight ]]"',
        # Deploy-only optional overrides (empty → fall back to CI/CD Variables).
        '  INPUT_INVENTORY_GIT_URL: "$[[ inputs.inventory_git_url ]]"',
        '  INPUT_INVENTORY_GIT_REF: "$[[ inputs.inventory_git_ref ]]"',
        '  INPUT_INVENTORY_DIR: "$[[ inputs.inventory_dir ]]"',
        "",
        "cache:",
        '  key: "${CI_COMMIT_REF_SLUG}-pip"',
        "  paths:",
        "    - .cache/pip",
        "    - .venv/",
        "",
        "include:",
        "  - local: examples/internal/gitlab-ci.jobs.yml",
        "",
    ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ids",
        type=Path,
        default=Path("examples/internal/seed/cluster-ids.txt"),
    )
    parser.add_argument(
        "--phases",
        type=Path,
        default=Path("examples/internal/seed/cluster-phases.json"),
    )
    parser.add_argument(
        "--limits",
        type=Path,
        default=Path("examples/internal/seed/cluster-limits.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("examples/internal/.gitlab-ci.yml"),
    )
    parser.add_argument(
        "--prefer",
        default="",
        help="Optional cluster id to list first (PREFER_CLUSTER_ID)",
    )
    args = parser.parse_args(argv)

    ids = [
        ln.strip()
        for ln in args.ids.read_text(encoding="utf-8").splitlines()
        if ln.strip() and not ln.strip().startswith("#")
    ]
    phases_raw = json.loads(args.phases.read_text(encoding="utf-8"))
    limits_raw = json.loads(args.limits.read_text(encoding="utf-8"))
    if not isinstance(phases_raw, dict):
        raise SystemExit("--phases must be a JSON object")
    if not isinstance(limits_raw, dict):
        raise SystemExit("--limits must be a JSON object")

    phases_map = {
        str(k): [str(p) for p in (v or [])]
        for k, v in phases_raw.items()
        if isinstance(v, list)
    }
    limits_map = {str(k): _limit_values(v) for k, v in limits_raw.items()}

    text = build_gitlab_ci(
        ids,
        phases_map,
        limits_map,
        prefer=(args.prefer or "").strip(),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    old = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
    args.output.write_text(text, encoding="utf-8")
    if old == text:
        print(f"generate_gitlab_ci: unchanged → {args.output}")
        return 0
    print(f"generate_gitlab_ci: wrote {args.output} ({len(ids)} cluster_id options)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
