"""Discover and merge cluster variables from Ansible group_vars/all/."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise RuntimeError("PyYAML required") from exc

from clusterctl.exceptions import ClusterctlError
from clusterctl.controller_extra_vars import strip_controller_contract_keys

# Sibling product basenames (orchestrated overlays = <name>.yml + <name>.secrets.yml).
CONVENTIONAL_PRODUCT_REPOS: tuple[str, ...] = (
    "atlas-compute-provision",
    "atlas-gitlab-runner",
    "atlas-infra-edge",
    "atlas-jenkins-agent",
    "atlas-k8s-addons",
    "atlas-k8s-core",
    "atlas-kafka",
    "atlas-node-foundation",
    "atlas-postgresql",
    "atlas-redis",
)

# Conventional leaf filenames (templates / docs). Discovery is not limited to this list.
# Product catalogs + per-product secrets. Legacy ``cluster.yml`` omitted since ADR 003 Phase 3
# (still merged if an old leaf keeps the file — see discover / optional_cluster_var_file).
CONVENTIONAL_GROUP_VARS_ALL: tuple[str, ...] = tuple(
    sorted(
        [f"{name}.yml" for name in CONVENTIONAL_PRODUCT_REPOS]
        + [f"{name}.secrets.yml" for name in CONVENTIONAL_PRODUCT_REPOS]
    )
)

# Legacy basename; optional since ADR 003 Phase 1 (removed from templates in Phase 3).
# Presence is validate ERROR (soft-compat Phase 4); still merged if present.
PRIMARY_CLUSTER_VAR = "cluster.yml"
# Legacy monolithic secrets — not merged (soft-compat Phase 4); validate ERROR if present.
SECRETS_VAR = "secrets.yml"
SECRETS_VAR_ALT = "secrets.yaml"
_LEGACY_SECRETS_BASENAMES = frozenset({SECRETS_VAR, SECRETS_VAR_ALT})
SECRETS_EXAMPLE = "secrets.yml.example"
PLAYBOOK_EXTRA_VARS_FILENAME = "cluster_playbook_vars.yaml"
PLAYBOOK_EXTRA_VARS_HEADER = (
    "# AUTO-GENERATED by clusterctl — edit group_vars/all on leaf and policy layers.\n"
    "# Merge: org default → env default → leaf (non-secrets), then *.secrets.yml (leaf last).\n"
    "# Materialized for ansible-playbook -e @ (play-level hosts: / global extra-vars scope).\n"
    "# Controller path keys are injected separately via controller_extra_vars.yaml.\n"
)

_GROUP_VARS_SUFFIXES = (".yml", ".yaml")


def group_vars_all_dir(config_dir: Path) -> Path:
    return config_dir / "group_vars" / "all"


def secrets_var_file(config_dir: Path) -> Path:
    """Legacy path ``group_vars/all/secrets.yml`` (migration / validate)."""
    return group_vars_all_dir(config_dir) / SECRETS_VAR


def secrets_example_file(config_dir: Path) -> Path:
    return group_vars_all_dir(config_dir) / SECRETS_EXAMPLE


def is_product_secrets_overlay(name: str) -> bool:
    """True for ``atlas-redis.secrets.yml`` / ``*.secrets.yaml``."""
    return name.endswith(".secrets.yml") or name.endswith(".secrets.yaml")


def is_legacy_secrets_overlay(name: str) -> bool:
    return name in _LEGACY_SECRETS_BASENAMES


def is_secrets_overlay(name: str) -> bool:
    """True for product ``*.secrets.yml`` overlays forced after catalogs in merge order."""
    return is_product_secrets_overlay(name)


def _is_group_vars_all_candidate(path: Path) -> bool:
    """True for mergeable var files under group_vars/all/."""
    if not path.is_file():
        return False
    name = path.name
    if name.startswith("."):
        return False
    if name.endswith(".example"):
        return False
    return name.endswith(_GROUP_VARS_SUFFIXES)


def _split_group_vars_all_dir(all_dir: Path) -> tuple[list[Path], list[Path]]:
    """Return (non-secrets, product-secrets) for one ``group_vars/all`` directory."""
    others: list[Path] = []
    secrets: list[Path] = []
    if not all_dir.is_dir():
        return others, secrets
    for path in sorted(all_dir.iterdir(), key=lambda p: p.name):
        if not _is_group_vars_all_candidate(path):
            continue
        if is_legacy_secrets_overlay(path.name):
            continue
        resolved = path.resolve()
        if is_product_secrets_overlay(path.name):
            secrets.append(resolved)
        else:
            others.append(resolved)
    return others, secrets


def discover_legacy_secrets_overlays(config_dir: Path) -> tuple[Path, ...]:
    """Legacy monolithic ``secrets.yml`` / ``secrets.yaml`` (not merged; validate ERROR)."""
    all_dir = group_vars_all_dir(config_dir)
    if not all_dir.is_dir():
        return ()
    found: list[Path] = []
    for path in all_dir.iterdir():
        if not _is_group_vars_all_candidate(path):
            continue
        if is_legacy_secrets_overlay(path.name):
            found.append(path.resolve())
    found.sort(key=lambda p: (0 if p.name == SECRETS_VAR_ALT else 1, p.name))
    return tuple(found)


def discover_secrets_overlays(config_dir: Path) -> tuple[Path, ...]:
    """
    Product secrets overlays under group_vars/all/ (alphabetical).

    Legacy monolithic ``secrets.yml`` / ``secrets.yaml`` are **not** merged
    (soft-compat Phase 4); see :func:`discover_legacy_secrets_overlays`.
    """
    _others, secrets = _split_group_vars_all_dir(group_vars_all_dir(config_dir))
    return tuple(secrets)


def discover_group_vars_all(config_dir: Path) -> tuple[Path, ...]:
    """
    Return group_vars/all/*.{yml,yaml} in materialize / validate merge order.

    Order matches Ansible's alphabetical load of files in the directory, except
    product secrets overlays are always appended last:

    1. non-secrets ``*.yml`` / ``*.yaml`` (alphabetical) — includes legacy
       ``cluster.yml`` if present (validate ERROR; soft-compat Phase 4)
    2. ``*.secrets.yml`` / ``*.secrets.yaml`` (alphabetical)

    Legacy monolithic ``secrets.yml`` is skipped (not merged).
    ``*.example`` and hidden files are skipped.
    """
    others, secrets = _split_group_vars_all_dir(group_vars_all_dir(config_dir))
    return tuple(others) + tuple(secrets)


def discover_group_vars_cascade(dirs: Sequence[Path]) -> tuple[Path, ...]:
    """
    Merge file list across org → env → leaf ``group_vars/all`` directories.

    Global order (later wins on shallow key merge):

    1. non-secrets per layer (org, then env, then leaf; alpha within layer)
    2. product ``*.secrets.yml`` per layer (org → env → leaf; alpha within layer)

    Legacy monolithic ``secrets.yml`` is skipped. Empty / missing dirs are ignored.
    """
    non_secrets: list[Path] = []
    secrets: list[Path] = []
    for all_dir in dirs:
        layer_others, layer_secrets = _split_group_vars_all_dir(Path(all_dir))
        non_secrets.extend(layer_others)
        secrets.extend(layer_secrets)
    return tuple(non_secrets) + tuple(secrets)


def optional_cluster_var_file(config_dir: Path) -> Path | None:
    """Return ``group_vars/all/cluster.yml`` when present (ADR 003 Phase 1).

    Identity SoT is ``atlas-*.yml``; this filename is optional legacy.
    Presence is validate ERROR (soft-compat Phase 4).
    """
    path = group_vars_all_dir(config_dir) / PRIMARY_CLUSTER_VAR
    return path.resolve() if path.is_file() else None


def primary_cluster_var_file(config_dir: Path) -> Path | None:
    """Deprecated alias for :func:`optional_cluster_var_file`.

    Prefer ``optional_cluster_var_file`` (ADR 003 / packaging Phase 6).
    """
    import warnings

    warnings.warn(
        "primary_cluster_var_file is deprecated; use optional_cluster_var_file",
        DeprecationWarning,
        stacklevel=2,
    )
    return optional_cluster_var_file(config_dir)


def require_group_vars_all(config_dir: Path) -> tuple[Path, ...]:
    """Discover mergeable group_vars or raise (leaf contract after ADR 003)."""
    files = discover_group_vars_all(config_dir)
    if not files:
        raise ClusterctlError(
            f"no group_vars found under {config_dir / 'group_vars' / 'all'} "
            f"(expected at least one atlas-*.yml / *.yml overlay; "
            f"see docs/adr/003-optional-cluster-yml.md)"
        )
    return files


def load_yaml_mapping(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ClusterctlError(f"expected YAML mapping: {path}")
    return data


def load_cluster_vars(
    config_dir: Path,
    *,
    cascade_dirs: Sequence[Path] | None = None,
) -> dict:
    """Merge group_vars/all overlays (Python-side SoT for validate/intent).

    When ``cascade_dirs`` is set (org → env → leaf ``group_vars/all``), use
    :func:`discover_group_vars_cascade`. Otherwise merge only ``config_dir``.
    """
    if cascade_dirs is not None:
        files = discover_group_vars_cascade(cascade_dirs)
    else:
        files = discover_group_vars_all(config_dir)
    merged: dict = {}
    for path in files:
        merged.update(load_yaml_mapping(path))
    return merged


def load_cluster_vars_from_paths(paths: tuple[Path, ...] | list[Path]) -> dict:
    """Merge explicit var file paths (tests / workspace_id helpers)."""
    merged: dict = {}
    for path in paths:
        if path.is_file():
            merged.update(load_yaml_mapping(path))
    return merged


def playbook_extra_vars_path(workspace_root: Path) -> Path:
    """Path to materialized group_vars/all merge for ansible ``-e @``."""
    return workspace_root.resolve() / ".ansible" / PLAYBOOK_EXTRA_VARS_FILENAME


def materialize_playbook_extra_vars(
    config_dir: Path,
    workspace_root: Path,
    *,
    cascade_dirs: Sequence[Path] | None = None,
    group_var_files: Sequence[Path] | None = None,
) -> Path:
    """
    Write merged group_vars/all to workspace for ansible-playbook extra-vars.

    Ansible cannot template play-level ``hosts:`` from inventory group_vars; extra-vars
    are globally scoped and match legacy ``-e @vars-file.yml`` behavior.

    Prefer ``group_var_files`` (pre-discovered cascade order) when available;
    else ``cascade_dirs``; else leaf-only ``config_dir``.
    """
    dest = playbook_extra_vars_path(workspace_root)
    if group_var_files is not None:
        merged = strip_controller_contract_keys(
            load_cluster_vars_from_paths(group_var_files)
        )
    else:
        merged = strip_controller_contract_keys(
            load_cluster_vars(config_dir, cascade_dirs=cascade_dirs)
        )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        PLAYBOOK_EXTRA_VARS_HEADER
        + yaml.safe_dump(merged, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return dest.resolve()


def validate_secrets_content(path: Path) -> str | None:
    """Return an error message when a secrets overlay exists but is not a YAML mapping."""
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return None
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        return f"secrets file is not valid YAML: {exc}"
    if data is None:
        return None
    if not isinstance(data, dict):
        return "secrets file must be a YAML mapping (dictionary)"
    return None


def secrets_file_configured(path: Path) -> bool:
    """True when a secrets overlay exists and contains at least one mapping key."""
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return False
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError:
        return False
    return isinstance(data, dict) and bool(data)
