"""Controller-injected extra-vars for sibling-repo playbook execution (schema v2)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise RuntimeError("PyYAML required") from exc

if TYPE_CHECKING:
    from clusterctl.context import ClusterContext

CONTROLLER_EXTRA_VARS_FILENAME = "controller_extra_vars.yaml"
CONTROLLER_EXTRA_VARS_HEADER = (
    "# AUTO-GENERATED by clusterctl — controller contract for sibling-repo playbooks.\n"
    "# Injected after cluster_playbook_vars.yaml (highest precedence).\n"
)

# Keys materialized from group_vars/all must not duplicate controller inject —
# Jinja derived from playbook_dir breaks when cwd is a sibling repo.
CONTROLLER_CONTRACT_KEYS: frozenset[str] = frozenset(
    {
        "atlas_cluster_root",
        "atlas_clusters_root",
        "atlas_inventory_root",
        "cluster_id",
        "cluster_config_dir",
        "cluster_inventory",
        "cluster_pub_keys_dir",
        "cluster_workspace_id",
        "cluster_workspace_parent",
        "cluster_workspace_root",
        "provision_hosts_file",
        "provision_ssh_public_key_file",
    }
)


def controller_extra_vars_path(workspace_root: Path) -> Path:
    return workspace_root.resolve() / ".ansible" / CONTROLLER_EXTRA_VARS_FILENAME


def build_controller_extra_vars(ctx: ClusterContext) -> dict[str, str]:
    from clusterctl.paths import (
        atlas_inventory_root as resolve_inventory_root,
        clusters_root as resolve_clusters_root,
        workspace_parent as resolve_workspace_parent,
    )

    pub_keys = ctx.config_dir / "pub_keys"
    repo_root = ctx.repo_root.resolve()
    config_dir = ctx.config_dir.resolve()
    inventory = ctx.inventory.resolve()
    pub_keys_dir = pub_keys.resolve()
    workspace_parent = resolve_workspace_parent(repo_root)
    workspace_root = ctx.workspace_root.resolve()
    ssh_pub = pub_keys / "localuser.pub"
    clusters = resolve_clusters_root(repo_root).resolve()
    inventory_root = resolve_inventory_root(repo_root).resolve()

    return {
        "atlas_cluster_root": str(repo_root),
        "atlas_clusters_root": str(clusters),
        "atlas_inventory_root": str(inventory_root),
        "cluster_id": ctx.cluster_id,
        "cluster_config_dir": str(config_dir),
        "cluster_inventory": str(inventory),
        "cluster_pub_keys_dir": str(pub_keys_dir),
        "cluster_workspace_id": ctx.workspace_id,
        "cluster_workspace_parent": str(workspace_parent),
        "cluster_workspace_root": str(workspace_root),
        "provision_hosts_file": str(inventory),
        "provision_ssh_public_key_file": str(ssh_pub),
    }


def strip_controller_contract_keys(merged: dict) -> dict:
    """Remove controller contract keys before materializing cluster_playbook_vars."""
    return {key: value for key, value in merged.items() if key not in CONTROLLER_CONTRACT_KEYS}


def materialize_controller_extra_vars(ctx: ClusterContext) -> Path:
    dest = controller_extra_vars_path(ctx.workspace_root)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        CONTROLLER_EXTRA_VARS_HEADER
        + yaml.safe_dump(
            build_controller_extra_vars(ctx),
            sort_keys=False,
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    return dest.resolve()


def validate_controller_contract(ctx: ClusterContext) -> list[str]:
    """Return human-readable errors when mandatory controller contract paths are missing."""
    errors: list[str] = []
    data = build_controller_extra_vars(ctx)

    repo_root = Path(data["atlas_cluster_root"])
    if not repo_root.is_dir():
        errors.append(f"atlas_cluster_root: not a directory: {repo_root}")

    config_dir = Path(data["cluster_config_dir"])
    if not config_dir.is_dir():
        errors.append(f"cluster_config_dir: not a directory: {config_dir}")

    inventory = Path(data["cluster_inventory"])
    if not inventory.is_file():
        errors.append(f"cluster_inventory: inventory not found: {inventory}")

    pub_keys = Path(data["cluster_pub_keys_dir"])
    if not pub_keys.is_dir():
        errors.append(f"cluster_pub_keys_dir: not a directory: {pub_keys}")
    else:
        ssh_pub = Path(data["provision_ssh_public_key_file"])
        if not ssh_pub.is_file():
            errors.append(
                f"provision_ssh_public_key_file: missing {ssh_pub.name} under {pub_keys}"
            )

    if not data["cluster_id"].strip():
        errors.append("cluster_id: empty")

    if not data["cluster_workspace_id"].strip():
        errors.append("cluster_workspace_id: empty")

    return errors


def controller_contract_warnings(ctx: ClusterContext) -> list[str]:
    """Non-fatal checks (workspace tree may not exist until first playbook run)."""
    warnings: list[str] = []
    data = build_controller_extra_vars(ctx)

    workspace_parent = Path(data["cluster_workspace_parent"])
    if not workspace_parent.is_dir():
        warnings.append(
            f"cluster_workspace_parent not created yet: {workspace_parent} "
            "(created on first run / workspace bootstrap)"
        )

    workspace_root = Path(data["cluster_workspace_root"])
    if not workspace_root.is_dir():
        warnings.append(
            f"cluster_workspace_root not created yet: {workspace_root} "
            "(created by 00_ensure_workspace on first run)"
        )
    return warnings
